/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const TestPageLazyImport = createFileRoute('/test-page')()
const LiveViewLazyImport = createFileRoute('/live-view')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const TestPageLazyRoute = TestPageLazyImport.update({
  path: '/test-page',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/test-page.lazy').then((d) => d.Route))

const LiveViewLazyRoute = LiveViewLazyImport.update({
  path: '/live-view',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/live-view.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/live-view': {
      id: '/live-view'
      path: '/live-view'
      fullPath: '/live-view'
      preLoaderRoute: typeof LiveViewLazyImport
      parentRoute: typeof rootRoute
    }
    '/test-page': {
      id: '/test-page'
      path: '/test-page'
      fullPath: '/test-page'
      preLoaderRoute: typeof TestPageLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/live-view': typeof LiveViewLazyRoute
  '/test-page': typeof TestPageLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/live-view': typeof LiveViewLazyRoute
  '/test-page': typeof TestPageLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/live-view': typeof LiveViewLazyRoute
  '/test-page': typeof TestPageLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/live-view' | '/test-page'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/live-view' | '/test-page'
  id: '__root__' | '/' | '/live-view' | '/test-page'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  LiveViewLazyRoute: typeof LiveViewLazyRoute
  TestPageLazyRoute: typeof TestPageLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  LiveViewLazyRoute: LiveViewLazyRoute,
  TestPageLazyRoute: TestPageLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/live-view",
        "/test-page"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/live-view": {
      "filePath": "live-view.lazy.tsx"
    },
    "/test-page": {
      "filePath": "test-page.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
